# Generated by Django 5.2.6 on 2025-09-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_user_phone_number_alter_tweet_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(null=True, verbose_name='電話番号'),
        ),
    ]
